version: "3.8"

services:
  sog:
    image: sog
    environment:
      # In docker, the server needs to be listening on all interfaces
      SOG_SERVER_HOST: "0.0.0.0"
      # SOG_SERVER_PORT: "8888"
      # SOG_SERVER_DIR: "/opt/sog"
      # SOG_SERVER_DATADIR: "/opt/sog/.data"
      # SOG_SERVER_LOGDIR: "/opt/sog/.logs"
      # SOG_SERVER_APP: "server.py"
    ports:
      - 8888:8888
    volumes:
      - ./sog/:/opt/sog
